Update dmenu-tran code format

diff --git a/.local/bin/dmenu-tran b/.local/bin/dmenu-tran
--- a/.local/bin/dmenu-tran
+++ b/.local/bin/dmenu-tran
@@ -1,16 +1,16 @@
 #!/bin/sh
 
 echo_err() {
-	notify-send -u critical "$0 error" "$1"
+    notify-send -u critical "$0 error" "$1"
 }
 
 err() {
-	echo_err "$1"
-	exit 1
+    echo_err "$1"
+    exit 1
 }
 
 check_dep() {
-	command -v "$1" > /dev/null || err "$1 is required: $2"
+    command -v "$1" >/dev/null || err "$1 is required: $2"
 }
 
 # We don't check if dmenu is installed because someone
@@ -19,76 +19,79 @@ check_dep trans https://github.com/soimort/translate-shell
 check_dep notify-send
 
 load_config() {
-	# Check others
-        : "${CLIP_COPY:=xclip -i -r -selection clipboard}"
-        : "${CLIP_PASTE_CLIP:=xclip -o -selection clipboard}"
-        : "${CLIP_PASTE_PRIM:=xclip -o -selection primary}"
-        : "${DMENU:=dmenu}"
-        : "${TERMINAL=st}"
+    # Check others
+    : "${CLIP_COPY:=xclip -i -r -selection clipboard}"
+    : "${CLIP_PASTE_CLIP:=xclip -o -selection clipboard}"
+    : "${CLIP_PASTE_PRIM:=xclip -o -selection primary}"
+    : "${DMENU:=dmenu}"
+    : "${TERMINAL=st}"
 
-	# Default values
-	: "${TRANS_LANGS:=:it :en}"
-	: "${DMENU_TEXT:=${DMENU} -i -p 'Translate: Text'}"
-	: "${DMENU_LANG:=${DMENU} -i -p 'Translate: Into'}"
-	: "${DMENU_NEXT:=${DMENU} -i -p 'Translate: Next?'}"
+    # Default values
+    : "${TRANS_LANGS:=:it :en}"
+    : "${DMENU_TEXT:=${DMENU} -i -p 'Translate: Text'}"
+    : "${DMENU_LANG:=${DMENU} -i -p 'Translate: Into'}"
+    : "${DMENU_NEXT:=${DMENU} -i -p 'Translate: Next?'}"
 }
 
 formatmenu() {
-	echo "$1" | tr '\n' '  ' | sed 's/\s\{3,\}//g; s/^\(.\{30\}\).\+/\1.../; s/$/\n/'
+    echo "$1" | tr '\n' '  ' | sed 's/\s\{3,\}//g; s/^\(.\{30\}\).\+/\1.../; s/$/\n/'
 }
 
 get_selection() {
-	[ -n "$1" ] && eval "$CLIP_PASTE_CLIP" || eval "$CLIP_PASTE_PRIM"
+    [ -n "$1" ] && eval "$CLIP_PASTE_CLIP" || eval "$CLIP_PASTE_PRIM"
 }
 
 clip_menu() {
-	{ formatmenu "$1"; formatmenu "$2"; } |
-		sed 's/^\s*$//; 1s/^./Primary: &/; 2s/^./Clipboard: &/' |
-		sed '/^$/d'
+    {
+        formatmenu "$1"
+        formatmenu "$2"
+    } |
+        sed 's/^\s*$//; 1s/^./Primary: &/; 2s/^./Clipboard: &/' |
+        sed '/^$/d'
 }
 
 lang_menu() {
-	echo "$TRANS_LANGS" | sed 's/\s\+/\n/g' | sed '/:/!s/^/:/'
-	echo '[Define]'
+    echo "$TRANS_LANGS" | sed 's/\s\+/\n/g' | sed '/:/!s/^/:/'
+    echo '[Define]'
 }
 
 choose_next() {
-	t="$1"
-	shift
-	if [ -n "$ALWAYS_COPY" ]; then
-		echo 'Copy'
-	else
-		eval "$DMENU_NEXT" "$@" <<-EOF
+    t="$1"
+    shift
+    if [ -n "$ALWAYS_COPY" ]; then
+        echo 'Copy'
+    else
+        eval "$DMENU_NEXT" "$@" <<-EOF
 			Copy: $(formatmenu "$t")
 			View
 		EOF
-	fi
+    fi
 }
 
 save_file() (
-	tmp="$(mktemp --tmpdir 'dmenu-translate.XXXXXX')"
-	echo "$1" > "$tmp"
-	echo "$tmp"
+    tmp="$(mktemp --tmpdir 'dmenu-translate.XXXXXX')"
+    echo "$1" >"$tmp"
+    echo "$tmp"
 )
 
 open_term() {
-	${TERMINAL} -e ${PAGER:-'less'} "$(save_file "$1")"
+    ${TERMINAL} -e ${PAGER:-'less'} "$(save_file "$1")"
 }
 
 get_text() {
-	echo "$2" | while IFS= read -r clip; do
-	[ "$1" = "$clip" ] && {
-		type="$(echo "$clip" | sed 's/^\(\w\+\):.*/\1/')"
-			case "$type" in
-				Primary)   echo "$primary"   ;;
-				Clipboard) echo "$clipboard" ;;
-			esac
-			exit 10
-		}
-	done
+    echo "$2" | while IFS= read -r clip; do
+        [ "$1" = "$clip" ] && {
+            type="$(echo "$clip" | sed 's/^\(\w\+\):.*/\1/')"
+            case "$type" in
+                Primary) echo "$primary" ;;
+                Clipboard) echo "$clipboard" ;;
+            esac
+            exit 10
+        }
+    done
 
-	# If not found, just echo text
-	[ $? -ne 10 ] && echo "$1"
+    # If not found, just echo text
+    [ $? -ne 10 ] && echo "$1"
 }
 
 # Config
@@ -109,9 +112,9 @@ target="$(lang_menu | eval "$DMENU_LANG" "$@")" || exit 0
 
 # If Define chosen, define term and exit
 [ "$target" = '[Define]' ] && {
-	dict="$(trans -dictionary "$text")"
-	open_term "$(trans -dictionary "$text")"
-	exit 0
+    dict="$(trans -dictionary "$text")"
+    open_term "$(trans -dictionary "$text")"
+    exit 0
 }
 
 # Translate text
@@ -119,9 +122,12 @@ translation="$(trans -b "$target" "$text")"
 [ -z "$translation" ] && err 'Failed to translate'
 
 case "$(choose_next "$translation" "$@")" in
-	'View')                open_term "$translation"; exit 0 ;;
-	'Copy'*)               output="$translation" ;;
-	*)                     exit 0 ;;
+    'View')
+        open_term "$translation"
+        exit 0
+        ;;
+    'Copy'*) output="$translation" ;;
+    *) exit 0 ;;
 esac
 
 echo "$output" | eval "$CLIP_COPY" || err 'Failed to copy! Is CLIP_COPY setting set properly?'
