Add --verbose flags and cleanup routine.

diff --git a/.local/bin/lmount b/.local/bin/lmount
--- a/.local/bin/lmount
+++ b/.local/bin/lmount
@@ -6,5 +6,13 @@ if [ "$#" -eq 0 ]; then
 fi
 
 sudo cryptsetup luksOpen $1 encrypted &&\
-mkdir -p $HOME/external &&\
-sudo mount /dev/mapper/encrypted $HOME/external
+mkdir -vp $HOME/external &&\
+sudo mount --verbose /dev/mapper/encrypted $HOME/external
+
+if [ $? -ne 0 ]; then
+        echo "Aborting.."
+        [ -d $HOME/external ] && rmdir -v $HOME/external
+        if ls /dev/mapper/encrypted 1>/dev/null 2>/dev/null; then
+                sudo cryptsetup luksClose $1
+        fi
+fi
